Python/Django/integration_project/apps/course/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_course$', views.add_course, name='add_course'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
    url(r'^comment/(?P<id>\d+)$', views.comment, name='comment'),
    url(r'^add_comment/(?P<id>\d+)$', views.add_comment, name='add_comment'),
]

Python/Django/integration_project/apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    # url(r'^goback$', views.goback),
    # url(r'^delete/(?P<id>\d+)$', views.delete),
]

Python/Django/integration_project/apps/testmodels/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
]

Python/Django/integration_project/integration_project/urls.py
from django.conf.urls import url, include
urlpatterns = [
    url(r'^', include('apps.testmodels.urls', namespace='testmodels')),
    url(r'^course/', include('apps.course.urls', namespace='course')),
    url(r'^login/', include('apps.login.urls', namespace='login')),
]

Python/Django/integration_project/apps/course/models.py
from __future__ import unicode_literals

from django.db import models
from ..login .models import User

# Create your models here.
class Course(models.Model):
	name= models.CharField(max_length=255)
	created_at= models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Description(models.Model):
	description= models.CharField(max_length=255)
	course =  models.ForeignKey(Course)
	created_at= models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
	comment= models.CharField(max_length=255)
	course =  models.ForeignKey(Course)
	created_at= models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

Python/Django/integration_project/apps/login/models.py
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Python/Django/integration_project/apps/testmodels/models.py
from __future__ import unicode_literals

from django.db import models
from ..login.models import User
from ..course.models import Course

class abc(models.Model):
    user = models.ForeignKey(User, related_name='user')
    course = models.ForeignKey(Course, related_name='course')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = RegistrationManager()

class RegistrationManager(models.Manager):
    def isregister(self, user_id, course_id):
        check = abc.objects.filter(user_id=user_id).filter(course_id=course_id)
        if not check:
            return True
        else:
            return False

Python/Django/integration_project/apps/course/views.py
from django.shortcuts import render, redirect
from .models import Course, Description, Comment

# Create your views here.
def index(request):
	context = {
		'results': Description.objects.all()
	}
	return render(request, 'course/index.html', context)
	
def add_course(request):
	course = Course.objects.create(name=request.POST['name'])
	print course.id
	Description.objects.create(description= request.POST['description'], course_id = course.id)
	return redirect('/')

def delete(request, id):
	Course.objects.get(id=id).delete()
	Description.objects.filter(course_id=id).delete()
	return redirect('/')

def comment(request, id):
	context={
			'course': Course.objects.get(id=id),
			'comments': Comment.objects.filter(course_id=id)
	}
	return render(request, 'course/comment.html', context)

def add_comment(request, id):
	Comment.objects.create(comment=request.POST['comment'],course_id=id)
	return redirect('/comment/{}'.format(id))

Python/Django/integration_project/apps/login/views.py
from django.shortcuts import render, redirect
import re
import bcrypt
from .models import User
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

def index(request):
    context = {
    "users":User.objects.all()
    }
    return render(request, 'login/index.html', context)

def register(request):
    if request.method == 'POST':
        request.session['first_name'] = request.POST['first_name']
        request.session['last_name'] = request.POST['last_name']
        request.session['email'] = request.POST['email']
        request.session['password'] = request.POST['password']
        request.session['confirm'] = request.POST['confirm']

        request.session['alert'] = ''
        request.session['alert1'] = 'Registration Success!'
        validation = True

        if len(request.session['first_name']) < 2 or len(request.session['last_name']) < 2:
            request.session['alert'] += '<p>Error(s):</p><p>Names cannot be less than 2 letter.</p>'
            validation = False
        if str.isalpha(str(request.session['first_name'])) == False or str.isalpha(str(request.session['last_name'])) == False:
            request.session['alert'] += '<p>Names cannot contain any numbers. </p>'
            validation = False
        if len(request.session['email']) < 1 or len(request.session['password']) < 1 or len(request.session['confirm']) < 1:
            request.session['alert'] += '<p>All fields are required and must not be blank.</p>'
            validation = False
        if not EMAIL_REGEX.match(request.session['email']):
            request.session['alert'] += '<p>Invalid email address.</p>'
            validation = False
        if len(request.session['password']) < 8:
            request.session['alert'] += '<p>Password should be 8 or more characters.</p>'
            validation = False
        if request.session['confirm'] != request.session['password']:
            request.session['alert'] += '<p>Passwords do not match.</p>'
            validation = False

        if validation == False:
            return redirect('/')
        if validation == True:
            hashed = bcrypt.hashpw(request.session['password'].encode(encoding="utf-8", errors="strict"), bcrypt.gensalt())
            User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], password=hashed)
            request.session['name'] = request.POST['first_name']
            request.session['suc'] = 'You have successfully registered.'
            return render(request, 'login/success.html')


def login(request):
    user = User.objects.filter(email=request.POST['log_email'])
    if bcrypt.checkpw(str(request.POST['log_password']), str(user[0].password)):
        request.session['suc'] = 'You have successfully logged in.'
        request.session['fail'] = ''
        return render(request, 'login/success.html')
    else:
        request.session['fail'] = 'The email and password you entered do not match! Please try again.'
        return redirect('/')

Python/Django/integration_project/apps/testmodels/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse
from .models import abc
from ..course.models import Course
from ..login.models import User

def index(request):
    context = {
        "users": User.objects.all(),
        "courses": Course.objects.all(),
        "register": abc.objects.all()
    }
    return render(request, 'testmodels/index.html', context)

def add(request):
    if request.method== 'POST':
        if adc.objects.isregister(request.POST['user'], request.POST['course']):
            abc.objects.create(user_id=request.POST['users'], course_id=request.POST['courses'])
        else:
            print "User has already registered."
        return redirect(reverse('testmodels:index'))

Python/Django/integration_project/apps/course/templates/course/comment.html
<!DOCTYPE html>
<html>
<head>
	<title>Comments</title>
</head>
<body>
<h2>Comments:</h2>

<form action='{%url 'course:add_comment' id=course.id}' method="POST">
{% csrf_token %}
<p><textarea name="comment" cols="50" rows="10"></textarea></p>
<p><input type="submit" value="Add comment"></p>
</form>
<h3>All Comments:</h3>
{% for comment in comments %}
<p>{{comment.comment}}</p>
{% endfor %}
</body>
</html>

Python/Django/integration_project/apps/course/templates/course/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Courses</title>
</head>
<body>
<h2>Course</h2>
<form action='{%url 'course:add_course'%}' method="POST">
{% csrf_token %}
	<p>Name: <input type="text" name="name"></p>
	<p>Description: </p>
	<p><textarea name="description" cols="50" rows="10"></textarea> </p>
	<p><input type="submit" value="Add"></p>
</form>
<p>Courses:</p>
<table>
{% for result in results %}
	<tr>
		<td>{{result.course.name}}</td>
		<td>{{result.description}}</td>
		<td>{{result.course.created_at}}</td>
		<td><a href='{%url 'course:delete' id=result.course.id}'> Remove</a></td>
		<td><a href='{%url 'course:comment' id=result.course.id}'> Comment</a></td>
	</tr>
	{% endfor %}
</table>

</body>
</html>

Python/Django/integration_project/apps/login/templates/login/index.html
<!-- Created by Jian Zhang @ Coding Dojo on 02/18/2017 -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Registration</title>
        <style>
            #error{
                color:red;
            }
        </style>
    </head>
    <body>
        <h1>Django Registration and Login Project</h1>
        <div id="reg">
            <h2>Registration</h2>
            <form action='{%url 'login:register'%}' method='post'>
                {% csrf_token %}
                First Name: <input type='text' name='first_name' />
                Last Name: <input type='text' name='last_name' />
                Email: <input type='text' name='email' />
                Password: <input type='text' name='password' />
                Confirm PW: <input type='text' name='confirm' />
                <input type='submit' value='Register' />
            </form>
        </div>
        <br />
        <div id="log">
            <h2>Login</h2>
            <form action='{%url 'login:login'%}' method='post'>
                {% csrf_token %}
                Email: <input type='text' name='log_email' />
                Password: <input type='text' name='log_password' />
                <input type='submit' value='Login' />
            </form>
            <br />
            {{request.session.fail}}
        </div>
        <div id='errors'>
            {{request.session.alert|safe}}
        </div>
    </body>
</html>

Python/Django/integration_project/apps/login/templates/login/success.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Success Login</title>
        <style>
            #second{
                color: green;
            }
        </style>
    </head>
    <body>
        <h1>
            Success! Welcome, {{request.session.name}}!
        </h1>
        <p id="second">
            {{request.session.suc}}
        </p>

    </body>
</html>