Python/Django/Restful/Restful/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.products.urls', namespace='products')),
]

Python/Django/Restful/apps/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addnew$', views.addnew, name='addnew'),
    url(r'^create$', views.create, name='create'),
    url(r'^goback$', views.goback, name='goback'),
    url(r'^show/(?P<id>\d+)$', views.show, name='show'),
    url(r'^edit/(?P<id>\d+)$', views.edit, name='edit'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name='remove'),
    url(r'^update/(?P<id>\d+)$', views.update, name='update'),
]

Python/Django/Restful/apps/products/models.py
from __future__ import unicode_literals

from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Python/Django/Restful/apps/products/views.py
from django.shortcuts import render, redirect
from .models import Product

def index(request):
    context = {
        "products": Product.objects.all()
    }
    return render(request, 'products/index.html', context)

def addnew(request):
    return render(request, 'products/new.html')

def create(request):
    if request.method == 'POST':
        Product.objects.create(name=request.POST['name'], description=request.POST['description'], price=request.POST['price'])
        return redirect('/')

def goback(request):
    return redirect('/')

def show(request, id):
    context = {
        "id": id,
        "product": Product.objects.get(id=id)
    }
    return render(request, 'products/detail.html', context)

def edit(request, id):
    context = {
        "id": id,
        "product": Product.objects.get(id=id)
    }
    return render(request, 'products/edit.html', context)

def remove(request, id):
    Product.objects.get(id=id).delete()
    return redirect('/')

def update(request, id):
    Product.objects.filter(id=id).update(name=request.POST['name'], description=request.POST['description'], price=request.POST['price'])
    return redirect('/')

Python/Django/Restful/apps/products/templates/products/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Product Details</title>
    </head>
    <body>
        <h2>Product {{product.id}}</h2>
        <p>Name: {{product.name}}</p>
        <p>Description: {{product.description}}</p>
        <p>Price: ${{product.price}}</p>
        <p><a href='{%  url 'products:edit' id=product.id %}'>Edit</a> | <a href='{%  url 'products:goback' %}'>Go Back</a></p>
    </body>
</html>

Python/Django/Restful/apps/products/templates/products/edit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Product Edit Page</title>
    </head>
    <body>
        <h2>Edit Product {{product.id}}</h2>
        <form action='{% url 'products:update' id=product.id %}' method='post'>
            {% csrf_token %}
            <p>Name: <input type="text" name="name" value="{{product.name}}"></p>
            <p>Desciption: <input type="text" name="description" value="{{product.description}}"></p>
            <p>Price: <input type="text" name="price" value="{{product.price}}"></p>
            <p><input type="submit" name="" value="Update"></p>
        </form>
        <td><a href='{%  url 'products:show' id=product.id %}'>Show</a> | <a href='{%  url 'products:goback' %}'>Back</a>
    </body>
</html>

Python/Django/Restful/apps/products/templates/products/index.html
<!-- Created by Jian Zhang @ Coding Codo on 02/21/2017 -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Restful Practice</title>
    </head>
    <body>
        <h2>Products</h2>
        <table>
            <tr>
                <td>Name</td>
                <td>Description</td>
                <td>Price</td>
                <td>Action</td>
            </tr>
            {% for product in products %}
            <tr>
                <td>{{product.name}}</td>
                <td>{{product.description}}</td>
                <td>${{product.price}}</td>
                <td><a href='{%  url 'products:show' id=product.id %}'>Show</a> | <a href='{%  url 'products:edit' id=product.id %}'>Edit</a> | <a href='{%  url 'products:remove' id=product.id %}'>Remove</a></td>
            </tr>
            {% endfor %}
        </table>
        <br />
        <a href='{%  url 'products:addnew' %}'>Add a new product</a>
    </body>
</html>

Python/Django/Restful/apps/products/templates/products/new.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>New Product Page</title>
    </head>
    <body>
        <h2>Add A New Product</h2>
        <form action='{% url 'products:create' %}' method='post'>
            {% csrf_token %}
            <p>Name: <input type="text" name="name" value=""></p>
            <p>Desciption: <input type="text" name="description" value=""></p>
            <p>Price: <input type="text" name="price" value=""></p>
            <p><input type="submit" name="" value="Create"></p>
        </form>
        <a href='{%  url 'products:goback' %}'>Go Back</a>
    </body>
</html>