Python/Django/Secrets/Secrets/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include("apps.secret.urls", namespace='secret')),
]

Python/Django/Secrets/apps/secret/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^create$', views.create, name='create'),
    url(r'^like/(?P<id>\d+)$', views.like, name='like'),
    url(r'^goto$', views.goto, name='goto'),
    url(r'^goback$', views.goback, name='goback'),
]

Python/Django/Secrets/apps/secret/models.py
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=255)
    confirm = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Secret(models.Model):
    post = models.TextField(max_length=1000)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Like(models.Model):
    user = models.ForeignKey(User)
    secret = models.ForeignKey(Secret, related_name='secret_like')

Python/Django/Secrets/apps/secret/views.py
from django.shortcuts import render, redirect
from django.db.models import Count
from .models import User, Secret, Like
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
import bcrypt


def index(request):
    context = {
        "user": User.objects.all()
    }
    return render(request, 'secret/index.html', context)

def register(request):
    if request.method == 'POST':
        request.session['alert'] = ''
        request.session['alert1'] = 'Registration Success!'
        validation = True

        if len(request.POST['first_name']) < 2 or len(request.POST['last_name']) < 2:
            request.session['alert'] += '<p>Error(s):</p><p>Names cannot be less than 2 letter.</p>'
            validation = False
        if str.isalpha(str(request.POST['first_name'])) == False or str.isalpha(str(request.POST['last_name'])) == False:
            request.session['alert'] += '<p>Names cannot contain any numbers. </p>'
            validation = False
        if len(request.POST['email']) < 1 or len(request.POST['password']) < 1 or len(request.POST['confirm']) < 1:
            request.session['alert'] += '<p>All fields are required and must not be blank.</p>'
            validation = False
        if not EMAIL_REGEX.match(request.POST['email']):
            request.session['alert'] += '<p>Invalid email address.</p>'
            validation = False
        if len(request.POST['password']) < 8:
            request.session['alert'] += '<p>Password should be 8 or more characters.</p>'
            validation = False
        if request.POST['confirm'] != request.POST['password']:
            request.session['alert'] += '<p>Passwords do not match.</p>'
            validation = False

        if validation == False:
            return redirect('/')

        if validation == True:
            hashed = bcrypt.hashpw(request.POST['password'].encode(encoding="utf-8", errors="strict"), bcrypt.gensalt())
            user = User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], password=hashed)
            print user.id
            request.session['id'] = user.id
            request.session['name'] = user.first_name
            request.session['suc'] = 'You have successfully registered.'
            context = {
                "secrets": Secret.objects.all().annotate(counter=Count('secret_like')).order_by('-created_at')[:10]
            }
            return render(request, 'secret/secrets.html', context)


def login(request):
    user = User.objects.filter(email=request.POST['log_email'])
    if bcrypt.checkpw(str(request.POST['log_password']), str(user[0].password)):
        request.session['suc'] = 'You have successfully logged in.'
        request.session['fail'] = ''
        context = {
            "secrets": Secret.objects.all().annotate(counter=Count('secret_like')).order_by('-created_at')[:10]
        }
        return render(request, 'secret/secrets.html', context)
    else:
        request.session['fail'] = 'The email and password you entered do not match! Please try again.'
        return redirect('/')

def create(request):
    Secret.objects.create(post=request.POST['secret'], user_id=request.session['id'])
    context = {
        "secrets": Secret.objects.all().annotate(counter=Count('secret_like')).order_by('-created_at')[:10]
    }
    return render(request, 'secret/secrets.html', context)

def like(request, id):
    Like.objects.create(user_id=request.session['id'], secret_id=id)
    Secret.objects.all().annotate(counter=Count('secret_like'))
    context = {
        "secrets": Secret.objects.all().annotate(counter=Count('secret_like')).order_by('-created_at')[:10]
    }
    return render(request, 'secret/secrets.html', context)

def goto(request):
    context = {
        "secrets": Secret.objects.all().annotate(counter=Count('secret_like')).order_by('-counter')[:10]
    }
    return render(request, 'secret/popular.html', context)

def goback(request):
    context = {
        "secrets": Secret.objects.all().annotate(counter=Count('secret_like')).order_by('-created_at')[:10]
    }
    return render(request, 'secret/secrets.html', context)

Python/Django/Secrets/apps/secret/templates/secret/index.html
<!-- Created by Jian Zhang @ Coding Dojo on 02/22/2017 -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Registration</title>
        <style>
            #error{
                color:red;
            }
        </style>
    </head>
    <body>
        <h1>Dojo Secret</h1>
        <div id="reg">
            <h2>Registration</h2>
            <form action='{% url 'secret:register' %}' method='post'>
                {% csrf_token %}
                <p>First Name: <input type='text' name='first_name' /></p>
                <p>Last Name: <input type='text' name='last_name' /></p>
                <p>Email: <input type='text' name='email' /></p>
                <p>Password: <input type='text' name='password' /></p>
                <p>Confirm PW: <input type='text' name='confirm' /></p>
                <p><input type='submit' value='Register' /></p>
            </form>
        </div>
        <br />
        <div id="log">
            <h2>Login</h2>
            <form action='{% url 'secret:login' %}' method='post'></p>
                {% csrf_token %}
                <p>Email: <input type='text' name='log_email' /></p>
                <p>Password: <input type='text' name='log_password' /></p>
                <p><input type='submit' value='Login' /></p>
            </form>
            <br />
            {{request.session.fail}}
        </div>
        <div id='errors'>
            {{request.session.alert|safe}}
        </div>
    </body>
</html>

Python/Django/Secrets/apps/secret/templates/secret/popular.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Most Popular Secrets</title>
    </head>
    <body>
        <h2> Most Popular Secrets..</h2>
        <a href='{%  url 'secret:goback' %}'>Back</a>
        {% for secret in secrets %}
        <p>"{{secret.post}}" ({{secret.created_at}}) | {{secret.counter}} likes</p>
        {% endfor %}
    </body>
</html>

Python/Django/Secrets/apps/secret/templates/secret/secrets.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h2>Hello! {{request.session.name}}</h2>
        <form action='{% url 'secret:create' %}' method="POST">
            {% csrf_token %}
            <p><textarea name="secret" cols="50" rows="10"></textarea></p>
            <p><input type="submit" value="Post"></p>
        </form>
        <a href='{%  url 'secret:goto' %}'>Most Popular Secrets</a>
        <h2>Recent Secrets</h2>
        {% for secret in secrets %}
        <p>"{{secret.post}}" ({{secret.created_at}}) | {{secret.counter}} likes <a href='{%  url 'secret:like' id=secret.id %}'>like</a> </p>
        {% endfor %}

    </body>
</html>