Python/Django/Bookreview/Bookreview/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.review.urls', namespace='review')),
]

Python/Django/Bookreview/apps/review/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^goto$', views.goto, name='goto'),
    url(r'^create$', views.create, name='create'),
    url(r'^main$', views.main, name='main'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^book/(?P<id>\d+)$', views.book, name='book'),
    url(r'^add/(?P<id>\d+)$', views.add, name='add'),
    url(r'^user/(?P<id>\d+)$', views.user, name='user'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
]

Python/Django/Bookreview/apps/review/models.py
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Review(models.Model):
    review = models.TextField(max_length=1000)
    rating = models.IntegerField()
    user = models.ForeignKey(User, related_name='useruser')
    book = models.ForeignKey(Book, related_name='bookbook')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Python/Django/Bookreview/apps/review/views.py
from django.shortcuts import render, redirect
from django.db.models import Count
from django.contrib import messages
from .models import User, Book, Review
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
import bcrypt

def index(request):
    return render(request, 'review/index.html')

def register(request):
    if request.method == 'POST':
        alert = []
        validation = True
        check_user = User.objects.filter(email=request.POST['email'])
        if check_user:
            alert.append('The user already exists, please try another email.')
            validation = False
        if len(request.POST['name']) < 2 or len(request.POST['alias']) < 2:
            alert.append('Names cannot be less than 2 letters.')
            validation = False
        if str.isalpha(str(request.POST['name'])) == False or str.isalpha(str(request.POST['alias'])) == False:
            alert.append('Names cannot contain any numbers.')
            validation = False
        if len(request.POST['email']) < 1 or len(request.POST['password']) < 1 or len(request.POST['confirm']) < 1:
            alert.append('All fields are required and must not be blank.')
            validation = False
        if not EMAIL_REGEX.match(request.POST['email']):
            alert.append('Invalid email address.')
            validation = False
        if len(request.POST['password']) < 8:
            alert.append('Password should be 8 or more characters.')
            validation = False
        if request.POST['confirm'] != request.POST['password']:
            alert.append('Passwords do not match.')
            validation = False


        if validation == False:
            for i in range(0, len(alert)):
                messages.error(request, alert[i])
            return redirect('/')

        if validation == True:
            hashed = bcrypt.hashpw(request.POST['password'].encode(encoding="utf-8", errors="strict"), bcrypt.gensalt())
            user = User.objects.create(name=request.POST['name'], alias=request.POST['alias'], email=request.POST['email'], password=hashed)
            request.session['email'] = request.POST['email']
            request.session['user_id'] = user.id
            request.session['name'] = user.name
            request.session['alias'] = user.alias
            context = {
                "user": User.objects.get(email=request.POST['email']),
                "books": Book.objects.all().order_by('-created_at')[:5],
                "reviews": Review.objects.all().order_by('-created_at')[:5],
                "boobs": Book.objects.all().order_by('title')
            }
            return render(request, 'review/main.html', context)


def login(request):
    user = User.objects.filter(email=request.POST['log_email'])
    if not user:
        messages.error(request, "The email you entered does not exist, please register!")
        return redirect('/')

    if bcrypt.checkpw(str(request.POST['log_password']), str(user[0].password)):
        context = {
            "user": User.objects.get(email=request.POST['log_email']),
            "books": Book.objects.all().order_by('-created_at')[:5],
            "reviews": Review.objects.all().order_by('-created_at')[:5],
            "boobs": Book.objects.all().order_by('title')
        }
        request.session['user_id'] = user[0].id
        request.session['name'] = user[0].name
        request.session['alias'] = user[0].alias
        request.session['email'] = request.POST['log_email']
        return render(request, 'review/main.html', context)

    else:
        messages.error(request, 'The email and password you entered do not match! Please try again.')
        return redirect('/')


def main(request):
    user = User.objects.filter(email=request.session['email'] )
    print request.session['user_id']

    context = {
        "books": Book.objects.all().order_by('-created_at')[:5],
        "reviews": Review.objects.all().order_by('-created_at')[:5],
        "boobs": Book.objects.all().order_by('title')
    }
    return render(request, 'review/main.html', context)


def goto(request):
    return render(request, 'review/review.html')


def create(request):
    if request.method == 'POST':
        book = Book.objects.create(title=request.POST['title'], author=request.POST['author'])
        request.session['book_id'] = book.id
        Review.objects.create(review=request.POST['review'], rating=request.POST['rating'], user_id=request.session.get('user_id'), book_id=request.session['book_id'])
        context = {
            "books": Book.objects.all().order_by('-created_at')[:5],
            "reviews": Review.objects.all().order_by('-created_at')[:5],
            "boobs": Book.objects.all().order_by('title')
        }
        return render(request, 'review/main.html', context)

def delete(request, id):
    Review.objects.filter(id=id).delete()
    return redirect('review:main')

def book(request, id):
    context = {
        "book": Book.objects.get(id=id),
        "reviews": Review.objects.filter(book_id=id).order_by('-created_at')
    }
    return render(request, 'review/book.html', context)

def add(request, id):
    if request.method == 'POST':
        context = {
            "book": Book.objects.get(id=id),
            "reviews": Review.objects.filter(book_id=id).order_by('-created_at')
        }
        Review.objects.create(review=request.POST['review'], rating=request.POST['rating'], user_id=request.session['user_id'], book_id=id)
        return render(request, 'review/book.html', context)

def user(request, id):
    counter = Review.objects.filter(user_id=id).count()
    context = {
        "user": User.objects.get(id=id),
        "reviews": Review.objects.filter(user_id=id).order_by('-created_at'),
        "counter": counter
    }
    return render(request, 'review/user.html', context)

def logout(request):
    request.session.pop('user_id')
    request.session.pop('name')
    request.session.pop('alias')
    request.session.pop('email')
    return redirect('/')

Python/Django/Bookreview/apps/review/templates/review/book.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Book Details</title>
    </head>
    <body>
        <h3><i>{{book.title}}</i></h3>
        <p>Author: {{book.author}}</p>
        <a href='{%  url 'review:main' %}'>Home</a> | <a href='{%  url 'review:logout' %}'>Logout</a>
        <br />
        <h3>Reviews:</h3>
        {% for review in reviews %}
        <hr />
        <p>{{review.rating}} stars</p>
        <p><a href='{%  url 'review:user' id=review.user_id %}'>{{review.user.name}}</a> says: <i>{{review.review}}</i></p>
        <p><i>Posted on {{review.created_at}} </i></p>
        {% endfor %}

        <form action='{% url 'review:add' id=book.id %}' method='post'>
            {% csrf_token %}
            <p>Review: <textarea name="review" cols="50" rows="10"></textarea></p>
            <p>Rating: <select name="rating">
                <option value='1'>1</option>
                <option value='2'>2</option>
                <option value='3'>3</option>
                <option value='4'>4</option>
                <option value='5'>5</option>
            </select> stars</p>
            <p><input type="submit" value="Submit Review"></p>
    </body>
</html>

Python/Django/Bookreview/apps/review/templates/review/index.html
<!-- Created by Jian Zhang @ Coding Dojo on 02/22/2017 -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Book Review Registration and Login Page</title>
        <style>
            .errors{
                color:red;
            }
        </style>
    </head>
    <body>
        <h1>Welcome!</h1>
        <div id="reg">
            <h2>Register</h2>
            <form action='{% url 'review:register' %}' method='post'>
                {% csrf_token %}
                <p>Name: <input type='text' name='name' /></p>
                <p>Alias: <input type='text' name='alias' /></p>
                <p>Email: <input type='text' name='email' /></p>
                <p>Password: <input type='text' name='password' /></p>
                <p>Password should be at least 8 characters</p>
                <p>Confirm PW: <input type='text' name='confirm' /></p>
                <p><input type='submit' value='Register' /></p>
            </form>
        </div>
        <br />
        <div id="log">
            <h2>Login</h2>
            <form action='{% url 'review:login' %}' method='post'></p>
                {% csrf_token %}
                <p>Email: <input type='text' name='log_email' /></p>
                <p>Password: <input type='text' name='log_password' /></p>
                <p><input type='submit' value='Login' /></p>
            </form>
            <br />
            <div class="errors">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>

    </body>
</html>

Python/Django/Bookreview/apps/review/templates/review/main.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Books Home</title>
        <style>
        #wrapper{
            display: flex;
        }

        #left{
            margin-left: 20px;
        }
        #right{
            height:360px;
            width:300px;
            text-align: center;
            border: 1px solid black;
            margin-left: 100px;
            margin-top: 20px;
        }
        #window{
            overflow-y:scroll;
            height:300px;
            width:300px;
        }

        </style>
    </head>
    <body>
        <div id="wrapper">
            <div id="left">
                <h2>Welcome, {{request.session.name}}, the {{request.session.alias}} :)</h2>
                <a href='{%  url 'review:goto' %}'>Add Book and Review</a> | <a href='{%  url 'review:logout' %}'>Logout</a>
                <br />
                <h3>Recent Book Reviews</h3>
                {% for review in reviews %}
                <p><i><a href='{%  url 'review:book' id=review.book_id %}'>{{review.book.title}}</a></i></p>
                <BLOCKQUOTE><p><a href='{%  url 'review:user' id=review.user_id %}'>{{review.user.name}}</a> says: {{review.review}}</p>
                <p>Rating: {{review.rating}} stars</p></BLOCKQUOTE>
                {% if request.session.user_id ==  review.user_id %}
                <a href="{%url 'review:delete' id=review.id%}">[Delete This Review]</a>
                {%endif%}
                {% endfor %}
            </div>
            <div id="right">
                <h3>Other Books with Reviews</h3>
                <div id="window">
                    {% for boob in boobs %}
                    <p><a href='{%  url 'review:book' id=boob.id %}'>{{boob.title}}</a></p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </body>
</html>

Python/Django/Bookreview/apps/review/templates/review/review.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Add Book and Review</title>
    </head>
    <body>
        <h2>Add a New Book Title and a Review</h2>
        <a href='{%  url 'review:main' %}'>Home</a> | <a href='{%  url 'review:logout' %}'>Logout</a>
        <form action='{%  url 'review:create' %}' method='post'>
            {% csrf_token %}
            <p>Book Title: <input type="text" name="title" value=""></p>
            <p>Author: <input type="text" name="author" value=""></p>
            <p>Review: <textarea name="review" cols="50" rows="10"></textarea></p>
            <p>Rating: <select name="rating">
                <option value='1'>1</option>
                <option value='2'>2</option>
                <option value='3'>3</option>
                <option value='4'>4</option>
                <option value='5'>5</option>
            </select> stars</p>
            <p><input type="submit" value="Add Book and Review"></p>
        </form>
    </body>
</html>

Python/Django/Bookreview/apps/review/templates/review/user.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>User Profiles</title>
    </head>
    <body>
        <a href='{%  url 'review:main' %}'>Home</a> | <a href='{%  url 'review:goto' %}'>Add Book and Review</a> | <a href='{%  url 'review:logout' %}'>Logout</a>
        <p>User Alias: {{user.alias}}</p>
        <p>Name: {{user.name}}</p>
        <p>Email: {{user.email}}</p>
        <p>Total reviews: {{counter}}</p>
        <br />
        <p><i>{{user.name}}</i> Posted Reviews on the following books:</p>
        {% for review in reviews %}
        <p><a href='{%  url 'review:book' id=review.book_id %}'>{{review.book.title}}</a></p>
        {% endfor %}
    </body>
</html>